package com.bluntsoftware.app.modules.karateschool.repository;

import com.bluntsoftware.app.modules.karateschool.domain.Contactinfo;
import com.bluntsoftware.lib.jpa.repository.GenericRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.beans.factory.annotation.Qualifier;
/**
* Repository interface for table: Contactinfo.
* @author autogenerated
*/

@Repository("karateschoolContactinfoRepository")
@Qualifier("karateschool")
//@RepositoryRestResource(collectionResourceRel="karateschool.Contactinfo", path="karateschool/Contactinfo")
public interface ContactinfoRepository extends GenericRepository<Contactinfo,Integer>  {

}