package com.bluntsoftware.app.modules.karateschool.repository;

import com.bluntsoftware.app.modules.karateschool.domain.Contactemail;
import com.bluntsoftware.lib.jpa.repository.GenericRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.beans.factory.annotation.Qualifier;
/**
* Repository interface for table: Contactemail.
* @author autogenerated
*/

@Repository("karateschoolContactemailRepository")
@Qualifier("karateschool")
//@RepositoryRestResource(collectionResourceRel="karateschool.Contactemail", path="karateschool/Contactemail")
public interface ContactemailRepository extends GenericRepository<Contactemail,Integer>  {

}