package com.bluntsoftware.app.modules.karateschool.repository;

import com.bluntsoftware.app.modules.karateschool.domain.Contactweb;
import com.bluntsoftware.lib.jpa.repository.GenericRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.beans.factory.annotation.Qualifier;
/**
* Repository interface for table: Contactweb.
* @author autogenerated
*/

@Repository("karateschoolContactwebRepository")
@Qualifier("karateschool")
//@RepositoryRestResource(collectionResourceRel="karateschool.Contactweb", path="karateschool/Contactweb")
public interface ContactwebRepository extends GenericRepository<Contactweb,Integer>  {

}